name = "labDTS24_25_emc"
authors = ["emc"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DTSSignals = "ffd6acfe-cf79-472d-9fe0-516ab33e97a0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Signals = "6303bc30-01ab-52eb-8b10-60e47555a8d1"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[compat]
DrWatson = "2.18.0"
julia = "1.10.5"
